config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'toronto_events/about_us', to: 'about_us#about_us'
  get 'toronto_events/contact', to: 'about_us#contact_us'

  post 'toronto_events/contact_us_form', to: 'about_us#contact_us_form'#, as: 'TorontoEvents_contact'

  get 'admin/hosts', to: 'admin#hosts'
  get 'admin/hosts_show'
  get 'admin/events', to: 'admin#events'
  get 'admin/caterers', to: 'admin#caterers'
  get 'admin/caterers_show' 
  post 'admin/approve_multiple', to: 'admin#approve_multiple'
  
  
  resources :subscribers, only: [:create]


  resources :events, except: :show


  resources :host_organizations, only: [:create]
  resources :caterers, only: [:create]

  resources :events, only: [:show] do 
    resources :admin_reviews, only: [:create, :update]
    delete 'admin_reviews/destroy', to: 'admin_reviews#destroy'
    patch 'admin_reviews/patch', to: 'admin_reviews#update'

    get 'bookmarked', to: 'events#bookmark_event'
    get 'attending', to: 'events#attending_event'
  end 

  get 'bookmarked_events', to: 'events#bookmark'
  get 'attending_events', to: 'events#attending'

end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caterer.rb
class Caterer < ApplicationRecord
    has_many :events
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord 
  
  scope :filtered, ->(query_params) { Event::Filter.new.filter(self, query_params) }  
  
    has_and_belongs_to_many :attending_users,
    join_table: 'events_users',
    class_name: 'User',
    inverse_of: :events_users

    has_and_belongs_to_many :bookmarked_users, 
    join_table: 'bookmarked_events',
    class_name: 'User',
    inverse_of: :bookmarked_events

    belongs_to :user
    belongs_to :host_organization
    belongs_to :caterer

    validates :name, :start_date, :end_date, :start_time, :end_time, :address, :host_organization, :caterer, presence: true
    validate :start_date_cannot_be_in_the_past
    validate :end_date_cannot_be_in_the_past
    validate :end_date_after_start_date
    validate :times_cannot_be_the_same
  
    before_update :generate_timestamp

    def start_date_cannot_be_in_the_past
        if start_date.present? && start_date < Date.today
          errors.add(:start_date, "can't be in the past")
        end
      end

      def end_date_cannot_be_in_the_past
        if end_date.present? && end_date < Date.today
          errors.add(:end_date, "can't be in the past")
        end
      end

     def end_date_after_start_date
         return if end_date.blank? || start_date.blank?
      if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

    def times_cannot_be_the_same
      if start_date == end_date && start_time >= end_time
       errors.add(:times, "cannot be the same and end time cannot be earlier than start time")
    end
    end 
  
  def generate_timestamp
    self.update_required_timestamp = DateTime.now
  end

end

app/models/host_organization.rb
class HostOrganization < ApplicationRecord
    has_many :events
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/random_guy.rb
class RandomGuy < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :attending_events,
  join_table: 'events_users',
    class_name: 'Event',
    inverse_of: :events_users
    has_and_belongs_to_many :bookmarked_events, 
    join_table: 'bookmarked_events',
    class_name: 'Event',
    inverse_of: :bookmarked_events
    has_many :events
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  before_save :default_admin
    def default_admin
   self.admin ||= false
end


def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.username = auth.info.name
  end
end

def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.google_oauth2"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
 end
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
    def home
    end 

    def about_us
    end 

    def contact_us
    end 

    def contact_us_form
        @random_guy = RandomGuy.new(contact_us_form_params)
        if @random_guy.save
            flash[:notice] = 'Message succesfully sent'
            redirect_to root_url
        else
            flash[:notice] = "Please try again"
        end 

    end 

    private 
    def contact_us_form_params
        params.require(:random_guys).permit(:first_name, :last_name, :email, :message)
    end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.where(is_approved: true).order(start_date: :desc).take(4)
  end

end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def show_svg(path)
        File.open("app/assets/images/#{path}", "rb") do |file|
          raw file.read
        end
    end
      
end

app/helpers/caterers_helper.rb
module CaterersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about_us/about_us.html.erb
<h2 class="about_us_title">TorontoEvents </h2>

<p>Toronto Events is a platform for the Toronto community to visit and find out about different events that are happening in Toronto. In addition, people are able to submit events to the website where the Admin will review these events and allow them to be seen by the general public. It is the perfect place to plan an evening out with friends or to show support for your favorite organization and enjoy a well catered meal on the side.</p>
<p> There are 3 different types of users that come to our website. The first type is just the casual visitor who wants to browse and see what’s going on in Toronto. The second type of user is a user that wants to actually post different upcoming events for the general public to see. These users can also bookmark events and mark the different events that they will be attending. The third type of user is the admin. The admin sends out emails to the users who post events requiring them to make changes to the events that they posted to conform with content standards. The admin also approves those events that qualify to go up on the site and deletes those that do not.
</p>

app/views/about_us/contact_us.html.erb
<% flash.each do |type, msg| %>
    <div><%= msg %></div>
<% end %>


<div class="form">
<div class="form_title"> Contact Us </div>
<p class="contact_statement"> Question, comment, or suggestion?  Fill out the form below, and we will try to get back to you as soon as possible. </p>

<%= form_for :random_guys, url: toronto_events_contact_us_form_path do |f| %>
    
    <div class="field">
    <%= f.label :first_name, :class => 'form_label'%>
    <%= f.text_field :first_name, autofocus: true, :class => 'form_box' %>
    </div>

    <div class="field">
    <%= f.label :last_name, :class => 'form_label'%>
    <%= f.text_field :last_name, :class => 'form_box' %>
    </div>
    
    <div class="field">
    <%= f.label :email, :class => 'form_label'%>
    <%= f.email_field :email, :class => 'form_box' %>
    </div>

    <div class="field">
    <%= f.label :message, :class => 'form_label'%>
    <%= f.text_area :message, :class => 'form_box' %>
    </div>

    <%= f.submit "Submit", :class => 'submit' %>
    <% end %>
    
</div>

app/views/about_us/home.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut fermentum velit, id euismod mauris. Ut quis accumsan sem. Vivamus quis lectus id augue tincidunt bibendum. Mauris sem quam, convallis eu arcu sit amet, placerat bibendum lectus. Nunc quis nisl rutrum, sodales orci vel, iaculis eros. Curabitur a dui risus. Praesent dui magna, rutrum vitae turpis vel, porta porta nisi. Aenean pulvinar metus suscipit felis malesuada, non hendrerit mauris rhoncus. Cras dictum mattis leo nec pharetra. Phasellus porta egestas congue.

Curabitur sed facilisis nulla, vitae varius leo. Nam a venenatis enim, eu venenatis massa. Aenean feugiat eu lacus vitae consequat. Pellentesque mattis fermentum lectus at accumsan. Vivamus velit justo, condimentum eget est ultricies, pretium viverra nisl. Nullam a nibh lobortis diam iaculis malesuada ac eget mi. Donec lobortis vel orci tempus rutrum. Suspendisse porta et eros at tincidunt.

In hac habitasse platea dictumst. Proin tellus eros, porttitor et ultricies id, fermentum a dui. Morbi efficitur sagittis sollicitudin. Fusce eleifend massa orci. Integer ligula massa, condimentum quis dapibus eget, rutrum sit amet tellus. Sed lacus dui, vehicula et convallis sed, dapibus quis lorem. Morbi nec rhoncus ante. Praesent tincidunt, risus sed vulputate pharetra, ligula sem faucibus justo, eu luctus lorem est a leo.

Sed laoreet finibus ex eget tristique. Proin vel ante id massa sodales fermentum ut a mauris. Nullam lacus diam, varius non neque posuere, dictum venenatis tortor. Aenean sit amet cursus odio. Ut quis nibh at purus maximus tempor sed sit amet diam. Nulla finibus ac nisi non sollicitudin. Sed at rutrum enim. Integer sit amet magna rhoncus, fermentum arcu vitae, porta dui. Suspendisse eu est dignissim ligula venenatis laoreet non sit amet nibh. Sed fringilla rhoncus aliquet.

Maecenas accumsan, nisl et commodo luctus, est sem pretium arcu, ut rhoncus purus ligula non metus. In accumsan accumsan augue, at viverra urna laoreet egestas. Cras ut interdum felis. Curabitur tortor purus, venenatis sit amet molestie id, vestibulum ut dolor. Morbi augue magna, luctus ac sapien nec, placerat facilisis turpis. Cras enim libero, consectetur at felis vitae, scelerisque euismod mauris. Cras nisl neque, sagittis vel commodo et, tincidunt a dolor. Nullam molestie massa at quam euismod, et pharetra justo efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras id suscipit velit, vitae suscipit lacus. Curabitur vel tempus metus. Integer semper commodo urna ut viverra. Sed rhoncus eget ante et imperdiet.</p>