config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'toronto_events/about_us', to: 'about_us#about_us'
  get 'toronto_events/contact', to: 'about_us#contact_us'

  post 'toronto_events/contact_us_form', to: 'about_us#contact_us_form'#, as: 'TorontoEvents_contact'

  get 'admin/hosts', to: 'admin#hosts'
  get 'admin/hosts_show'
  get 'admin/events', to: 'admin#events'
  get 'admin/caterers', to: 'admin#caterers'
  get 'admin/caterers_show' 
  post 'admin/approve_multiple', to: 'admin#approve_multiple'
  
  
  resources :subscribers, only: [:create]


  resources :events, except: :show


  resources :host_organizations, only: [:create]
  resources :caterers, only: [:create]

  resources :events, only: [:show] do 
    resources :admin_reviews, only: [:create, :update]
    delete 'admin_reviews/destroy', to: 'admin_reviews#destroy'
    patch 'admin_reviews/patch', to: 'admin_reviews#update'

    get 'bookmarked', to: 'events#bookmark_event'
    get 'attending', to: 'events#attending_event'
  end 

  get 'bookmarked_events', to: 'events#bookmark'
  get 'attending_events', to: 'events#attending'

end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caterer.rb
class Caterer < ApplicationRecord
    has_many :events
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord 
  
  scope :filtered, ->(query_params) { Event::Filter.new.filter(self, query_params) }  
  
    has_and_belongs_to_many :attending_users,
    join_table: 'events_users',
    class_name: 'User',
    inverse_of: :events_users

    has_and_belongs_to_many :bookmarked_users, 
    join_table: 'bookmarked_events',
    class_name: 'User',
    inverse_of: :bookmarked_events

    belongs_to :user
    belongs_to :host_organization
    belongs_to :caterer

    validates :name, :start_date, :end_date, :start_time, :end_time, :address, :host_organization, :caterer, presence: true
    validate :start_date_cannot_be_in_the_past
    validate :end_date_cannot_be_in_the_past
    validate :end_date_after_start_date
    validate :times_cannot_be_the_same
  
    before_update :generate_timestamp

    def start_date_cannot_be_in_the_past
        if start_date.present? && start_date < Date.today
          errors.add(:start_date, "can't be in the past")
        end
      end

      def end_date_cannot_be_in_the_past
        if end_date.present? && end_date < Date.today
          errors.add(:end_date, "can't be in the past")
        end
      end

     def end_date_after_start_date
         return if end_date.blank? || start_date.blank?
      if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

    def times_cannot_be_the_same
      if start_date == end_date && start_time >= end_time
       errors.add(:times, "cannot be the same and end time cannot be earlier than start time")
    end
    end 
  
  def generate_timestamp
    self.update_required_timestamp = DateTime.now
  end

end

app/models/host_organization.rb
class HostOrganization < ApplicationRecord
    has_many :events
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/random_guy.rb
class RandomGuy < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :attending_events,
  join_table: 'events_users',
    class_name: 'Event',
    inverse_of: :events_users
    has_and_belongs_to_many :bookmarked_events, 
    join_table: 'bookmarked_events',
    class_name: 'Event',
    inverse_of: :bookmarked_events
    has_many :events
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  before_save :default_admin
    def default_admin
   self.admin ||= false
end


def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.username = auth.info.name
  end
end

def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.google_oauth2"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
 end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def show_svg(path)
        File.open("app/assets/images/#{path}", "rb") do |file|
          raw file.read
        end
    end
      
end

app/helpers/caterers_helper.rb
module CaterersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_new_host.html.erb
<%= form_for @new_host,  host_organization_index_path, method: :post,  do |f| %>
    <%= f.submit 'Create organziation' %>
<% end %>

app/views/admin/caterers.html.erb
<h1> Caterers </h1>

<% @caterers.each do |caterer| %>
        <ul>
        <li> <u> <%= link_to "#{caterer.name}" ,  admin_caterers_show_path(id: caterer.id),  :class => 'item'  %> </u> </li> 
        </ul>
<% end %>


<h2> Create Caterer </h2>
<%= form_for(@caterer, :url => caterers_path) do |f| %>

        <%= f.label 'Name' %>
        <br>
        <%= f.text_field 'name' %>
        <BR>
        <%= f.label 'Website URL' %>
        <br>
        <%= f.text_field 'website' %>
        <BR>
        <%= f.label 'Email address' %>
        <br>
        <%= f.email_field 'email' %>
        <BR>
        <%= f.label 'Mailing address' %>
        <br>
        <%= f.text_field 'mailing_address' %>
        <BR>
        <%= f.label 'Phone' %>
        <br>
        <%= f.text_field 'phone_number' %>
        <BR>
        <%= f.label 'Description' %>
        <br>
        <%= f.text_area 'description', size: "35x8" %>
        <BR>
        <%= f.submit 'Create caterer' %>
    
    <% end %>

app/views/admin/caterers_show.html.erb
<h1> Caterer </h1>
      <p> Name:  <%= @caterer.name %> </p> 
        <p> Website: <%= @caterer.website %> </p>
        <p> Email: <%= @caterer.email %> </p>
        <p> Mailing Address: <%= @caterer.mailing_address %> </p>
        <p> Phone: <%= @caterer.phone_number %> </p>
        <p> Description: <%= @caterer.description %> </p>
<p> Back to all <u> <%= link_to "all caterers", admin_caterers_path, :class => 'item' %> </u> </p>

app/views/admin/events.html.erb
<%= javascript_pack_tag 'update-form' %>

<h1> Events Pending Approval </h1>




<table style="width:100%" class = 'table'>

<thead>
<tr style = 'height:40px'>
    <th> Checkbox </th>
    <th style="width:15%"> Event name </th>
    <th style="width:15%"> Start Date and Time </th>
    <th style="width:15%"> End Date and Time </th>
    <th style="width:15%"> Required update explanation</th>
    <th style="width:15%"> Actions </th>
</tr>
</thead>



<tbody>
<% @events.each do |event| %>
    <tr style = 'height: auto'>
        <td>
            <%= check_box(event, :checkbox, checked_value: true, unchecked_value: false) %>
        </td>
        <td> 
            <u> 
                <%= link_to "#{event.name}", event_path(id: event.id),  :class => 'item' %> 
            </u> 
        </td>

        <td>
            <%= "#{event.start_date} #{event.start_time.strftime("%I:%M %p")}" %>
        </td>

        <td>
            <%= "#{event.end_date} #{event.end_time.strftime("%I:%M %p")}" %>
        </td>

        <td>
            <%= event.update_required_explanation %>
        </td>

        <td class="admin">
        <%= form_for event, url: event_admin_reviews_path(event.id), method: :post, :data => {confirm: 'Are you sure that you would like to approve this event?'} do |f| %>
            <%= image_submit_tag("check.png", class: 'admin-action') %> 
        <% end %>

        <%= form_for event, url: event_admin_reviews_destroy_path(event.id), method: :delete, :data => {confirm: 'Are you sure you would like to delete this event? '} do |f| %>
             <%= image_submit_tag("trash.png", class: 'admin-action') %>
        <% end %>

        <% if event.does_require_update == false %>
            <%= image_tag "refresh.png", class: "button  admin-action", id: "#{event.id}" %>
            
            <div class = 'update-div div<%= event.id%>'>
            <%= form_for event, url: event_admin_reviews_patch_path(event.id), method: :put,  :html => { :class => "Form Form#{event.id}" } do |f| %> 
                <%= image_tag 'logout.png', class: "admin-action logout logout#{event.id}" %>

                <div class = 'insideDiv' >
                <div class = 'Top'>
                <h3 class = 'eventName' > <%=event.name%> </h3>
                </div>
                <div class = 'Bottom'>
                <br>
                <h3><%= f.label :update_required_explanation %></h3>
                <%= f.text_area :update_required_explanation, size: "38x8", placeholder: 'Please explain what exactly you would like updated...' %>
                <%= f.submit "Request Update", class: 'requireUpdateButton' %>
                </div>
                </div>

                <% end %> 
            </div>

            <% end %>

        </td>
    </tr>
<% end %>
</tbody>



</table>

app/views/admin/hosts.html.erb
<h1> Host Organizations </h1>

<% @hosts.each do |event| %>
    <ul>
        <li> <u> <%= link_to "#{event.name}" , admin_hosts_show_path(id: event.id),  :class => 'item'  %> </u> </li> 
    </ul>
<% end %>   


<h2> Create Host Organization </h2>
<%= form_for(@host, :url => host_organizations_path) do |f| %>

    <%= f.label 'Name' %>
    <br>
    <%= f.text_field 'name' %>
    <BR>
    <%= f.label 'Website URL' %>
    <br>
    <%= f.text_field 'website' %>
    <BR>
    <%= f.label 'Email address' %>
    <br>
    <%= f.email_field 'email' %>
    <BR>
    <%= f.label 'Mailing address' %>
    <br>
    <%= f.text_field 'mailing_address' %>
    <BR>
    <%= f.label 'Phone' %>
    <br>
    <%= f.text_field 'phone_number' %>
    <BR>
    <%= f.label 'Brief Description of Organizations' %>
    <br>
    <%= f.text_area 'description', size: "35x8" %>
    <BR>
    <%= f.submit 'Create organization' %>

<% end %>

app/views/admin/hosts_show.html.erb
<h1> Host Organization </h1>


    
         <p> Name: <%= @host.name %> </p>
         <p> Website URL: <u> <%= @host.website %> </u> </p>
         <p> Email: <%= @host.email %> </p>    
         <p> Mailing address: <%= @host.mailing_address %> </p>
         <p> Phone number: <%= @host.phone_number %> </p>
         <p> Description: <%= @host.description %> </p> 


<p> Return to <u> <%= link_to ' All Hosts', admin_hosts_path, :class => 'item' %> </u> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>TorontoEvents</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script src="https://kit.fontawesome.com/a5ac8db979.js" crossorigin="anonymous"></script>
  </head>

 <body>
  <div class="app_header">
    <div class="app_nav">
      <div class="app_logo">
        <h2> <%= link_to "Toronto Events", root_path%> </h2>      
      </div>
      <div class="app_nav_menu">

           <% if current_user && current_user.admin %>

      <ul>
        <li>
            <%= link_to "Pending Events", admin_events_path, :class => 'item' %>
        </li>
        <li>
            <%= link_to "Host Organization's", admin_hosts_path, :class => 'item' %>
        </li>
        <li>
            <%= link_to "Caterers", admin_caterers_path, :class => 'item' %>
        </li>
      </ul>

         <% else %>
         <ul>
         <li>
             <%= link_to "Events", events_path %>
         </li>
         <li>
             <%= link_to "Create Event", new_event_path %>
         </li>
         <li>
             <%= link_to "Contact us", toronto_events_contact_path %>
         </li>
       </ul>

       <% end %>
      </div>

      <% if current_user %>
      <div class="dropdown">
      <button class="dropbtn"><p class="logged_in_user_greeting"> Hi <%= current_user.username%> <%= image_tag("user_icon_150670.png", :class => 'user_icon') %> <i class="fa fa-caret-down"></i> </p> 
        
      </button>
      <div class="dropdown-content">
       
        <%= link_to "Bookmarked Events", bookmarked_events_path%>
        <%= link_to "Attending Events", attending_events_path %>
        <%= link_to "Log out", destroy_user_session_path , method: :delete%>
      
      </div>
    </div> 
        
      <% else %>
        <div class="app_login_options">
          <ul>
            <li>
            <%= link_to "Sign up", new_user_registration_path, :class=> "signup" %>
            </li>
            <li>
                <%= link_to "Login", new_user_session_path, :class=> "login" %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="app_header_main">
      <div>
        <p class="topHeadline">
          Explore and Construct
        </p>
        <p class="topSubline"> 
          Take part in upcoming events, or generate your own to share
        </p>
      </div> 
    </div>

    <div class="app_header_bottom">
      <div id="topEventsButtons">
        <%= link_to "Browse Events", events_path, :class=>'topBrowseEventsButton'%>
        <%= link_to "Create Event", new_event_path, :class=>'topCreateEventButton' %>
      </div>
    </div>
  </div>


<div class="mainContainer">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>


  <div class = 'bottom'>
      <div class = 'copyrightLogo'>
       <p> <%= image_tag("Copyright.png", :class => 'icon')%> <span>TorontoEvents2021</span></p>  
      </div>

      <div class= 'subscribe'>
        <p class="subscribe_text"> Get email updates on the latest upcoming events! </p>
        <%= form_for :subscriber, url: subscribers_path do |f| %>
          <%= f.email_field :Email, placeholder: "email@example.com", :class => 'emailforsubscribe' %>
          <%= f.submit "Subscribe", :class => 'subscribeButton' %>
        <% end %>
      </div>

      <div class = 'bottomNav'>
        <ul>
          <li>
            <%= link_to "Home", root_path, :class => 'bottomNavBarItem' %>
          </li>
          <li>
            <%= link_to "About us", toronto_events_about_us_path, :class => 'bottomNavBarItem' %>
          </li>
          <li>
            <%= link_to "Contact us", toronto_events_contact_path, :class => 'bottomNavBarItem' %>
          </li>
        </ul>
      </div>
      
        
  </div>
  </body>
</html>