config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'toronto_events/about_us', to: 'about_us#about_us'
  get 'toronto_events/contact', to: 'about_us#contact_us'

  post 'toronto_events/contact_us_form', to: 'about_us#contact_us_form'#, as: 'TorontoEvents_contact'

  get 'admin/hosts', to: 'admin#hosts'
  get 'admin/hosts_show'
  get 'admin/events', to: 'admin#events'
  get 'admin/caterers', to: 'admin#caterers'
  get 'admin/caterers_show' 
  post 'admin/approve_multiple', to: 'admin#approve_multiple'
  
  
  resources :subscribers, only: [:create]


  resources :events, except: :show


  resources :host_organizations, only: [:create]
  resources :caterers, only: [:create]

  resources :events, only: [:show] do 
    resources :admin_reviews, only: [:create, :update]
    delete 'admin_reviews/destroy', to: 'admin_reviews#destroy'
    patch 'admin_reviews/patch', to: 'admin_reviews#update'

    get 'bookmarked', to: 'events#bookmark_event'
    get 'attending', to: 'events#attending_event'
  end 

  get 'bookmarked_events', to: 'events#bookmark'
  get 'attending_events', to: 'events#attending'

end

app/models/event.rb
class Event < ApplicationRecord 
  
  scope :filtered, ->(query_params) { Event::Filter.new.filter(self, query_params) }  
  
    has_and_belongs_to_many :attending_users,
    join_table: 'events_users',
    class_name: 'User',
    inverse_of: :events_users

    has_and_belongs_to_many :bookmarked_users, 
    join_table: 'bookmarked_events',
    class_name: 'User',
    inverse_of: :bookmarked_events

    belongs_to :user
    belongs_to :host_organization
    belongs_to :caterer

    validates :name, :start_date, :end_date, :start_time, :end_time, :address, :host_organization, :caterer, presence: true
    validate :start_date_cannot_be_in_the_past
    validate :end_date_cannot_be_in_the_past
    validate :end_date_after_start_date
    validate :times_cannot_be_the_same
  
    before_update :generate_timestamp

    def start_date_cannot_be_in_the_past
        if start_date.present? && start_date < Date.today
          errors.add(:start_date, "can't be in the past")
        end
      end

      def end_date_cannot_be_in_the_past
        if end_date.present? && end_date < Date.today
          errors.add(:end_date, "can't be in the past")
        end
      end

     def end_date_after_start_date
         return if end_date.blank? || start_date.blank?
      if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

    def times_cannot_be_the_same
      if start_date == end_date && start_time >= end_time
       errors.add(:times, "cannot be the same and end time cannot be earlier than start time")
    end
    end 
  
  def generate_timestamp
    self.update_required_timestamp = DateTime.now
  end

end

app/models/event/filter.rb
class Event::Filter

    def filter(scope, query_params)

      if query_params[:name].present?
        puts 'name is present'
        scope = scope.where("name LIKE ?", "%#{query_params[:name]}%")
      end

      if query_params[:address].present?
        puts 'address is present'
        scope = scope.where("address LIKE ?", "%#{query_params[:address]}%")
      end

      if query_params[:start_date].present?
        puts 'start date is present'
        scope = scope.where("start_date LIKE ?", "%#{query_params[:start_date]}%")
      end

      if scope.present? 
        return scope
      else 
        return Event.where(is_approved: true)
      end 
      
    end
  
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :delete, :show, :index]

    def index
        @events = Event.filtered(query_params)
    end


    def show
        @event = Event.find(params[:id])
        @host_organization = @event.host_organization
        @caterer = @event.caterer
    end
    

    def new
        @event = Event.new
    end

   
    def create
        @event = Event.new(event_params)
        @event.user = current_user
        if @event.save
            redirect_to events_url
        else
            render :new
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])
        if @event.update_attributes(event_params)
            redirect_to "/events/#{@event.id}"
        else
            render :edit
        end
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy
        redirect_to events_url
    end

    def bookmark_event
        @event = Event.find(params[:event_id])
       if !current_user.bookmarked_events.include?(@event)
        current_user.bookmarked_events << @event
        flash[:notice] = 'Successfuly Bookmarked'
       else
        current_user.bookmarked_events.delete(@event)
        flash[:notice] = 'Removed from bookmark list'
       end
       redirect_to "/events/#{@event.id}"
    end

    def attending_event
        @event = Event.find(params[:event_id])
        if !current_user.attending_events.include?(@event)
         current_user.attending_events << @event
         flash[:notice] = 'Marked attending'
        else
         current_user.attending_events.delete(@event)
         flash[:notice] = 'Removed from attending list'
        end
        redirect_to "/events/#{@event.id}"
    end

    def attending
        @events = current_user.attending_events
    end

    def bookmark
        @events = current_user.bookmarked_events
    end
  
   private
    def query_params
    query_params = params
    query_params ? query_params.permit(:name, :address, :start_date) : {}
    end
  
    def event_params
        params.require(:event).permit(:name, :start_date, :end_date, :start_time, :end_time, :address, :description, :host_organization_id, :caterer_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.html.erb
<%= javascript_pack_tag "events" %>

<div class="container">
<% @events.each do |event| %>
  
    <div class="event" id=<%= event.id %> >
        <p class="name"> <%= link_to event.name, event_path(event.id) %> </p>
        <div class="event_info">
            <p> <%= event.start_date %> - <%= event.start_time.strftime("%I:%M %p") %> </p>
            <p> <%= event.end_date %> - <%= event.end_time.strftime("%I:%M %p") %></p>
        </div>
   </div>
<%end%>      
</div>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
    <p class="field">
    <%= f.label :name %> <br>
    <%= f.text_field :name, autofocus: true, class: 'form_box' %>
    </p>
    <div class="field times">
    <div>
    <%= f.label :start_date %> <br>
    <%= f.date_field :start_date, class: 'form_box' %>
    </div>
  <div>
    <%= f.label :start_time %> <br>
    <%= f.time_field :start_time, class: 'form_box'%>
    </div>
    </div>

    <div class="field times">
    <div>
    <%= f.label :end_date %> <br>
    <%= f.date_field :end_date, class: 'form_box' %>
    </div>
    <div>
    <%= f.label :end_time %> <br>
    <%= f.time_field :end_time, class: 'form_box' %>
    </div>
    </div>

    <p class="field">
    <%= f.label :address %> <br>
    <%= f.text_field :address, class: 'form_box' %>

    </p>
    
    <p class="field">
    <%= f.label :description %> <br>
    <%= f.text_area :description , class: 'form_box '%>
    </p>
    <p class="field">
    <%= f.label :host_organization %> <br>
    <%= f.collection_select :host_organization_id, HostOrganization.all, :id, :name, {:prompt => "Please select a Host Organization"}, class: 'form_box' %>
    </p>
    <p class="field">
    <%= f.label :caterer %> <br>
    <%= f.collection_select :caterer_id, Caterer.all, :id, :name, {:prompt => "Please select a Caterer"}, class: 'form_box' %>
    </p>
    <div class="actions">
    <%= f.submit "Submit", class: 'submit' %>
    </div>
    <% end %>

app/views/events/attending.html.erb
<h1> Attending Events </h1>
<% if @events.empty? %>
<p>No Events Marked Attending Yet </p>
<%end%>
<%= render "events" %>

app/views/events/bookmark.html.erb
<h1> Bookmarked Events </h1>
<% if @events.empty? %>
<p>No Events Bookmarked Yet </p>
<%end%>
<%= render "events" %>

app/views/events/edit.html.erb
<h1 class="form_title">Edit your Event</h1>

<div class="events_form">
<%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="search_container">

<%= form_tag events_path, :method => 'get'  do %>

    <div class="search_form_box">
    <%= label_tag 'Event name'%>
    <%= text_field_tag :name %>
    </div>
    <div class="search_form_box">
    <%= label_tag 'Address' %>
    <%= text_field_tag :address%>
    </div>
    <div class="search_form_box">
    <%= label_tag 'Start date'  %>
    <%= date_field_tag :start_date%>
    </div>

    <div class="search_submit">
    <%= button_tag(type: "submit") do %>
        <%= image_tag 'search.png' %>
    <% end %>
    </div>
<% end %>
</div>

<%= render "events" %>

app/views/events/new.html.erb
<link rel="stylesheet" type="text/css" href="http://ws1.postescanada-canadapost.ca/css/addresscomplete-2.30.min.css?key=xu36-fp78-xc63-gf59" /><script type="text/javascript" src="http://ws1.postescanada-canadapost.ca/js/addresscomplete-2.30.min.js?key=xu36-fp78-xc63-gf59"></script>
<h1 class="form_title"> Add a New Event </h1>

<% if @event.errors.any? %>
<ul class="error_messages">
<% @event.errors.full_messages.each do |m| %>
    <li> <%= m %> </li>
    <%end%>
    </ul>
<%end%>
<div class="events_form">
<%= render 'form' %>
</div>

app/views/events/show.html.erb
<%= javascript_pack_tag "googlemaps" %>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyByjwkYLV7LF8vzH8hRkJKkD0e0xMbmx8o"></script>

<h1>  <%= @event.name %> </h1>
<div class="ShowContainer">
<div class="Textcontent">

<% if current_user.events.include?(@event) %>
<div class="links">
    <%= link_to "Edit", edit_event_path(@event) %>  
    <%= link_to "Delete", @event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} %>
</div>
<%end%>

<div>
        <p> <label> Start Date: </label> </p>
        <p> <%= @event.start_date %> <%= @event.start_time.strftime("%I:%M %p") %></p>

        <p> <label> End Date: </label> </p>
        <p> <%= @event.end_date %>  <%= @event.end_time.strftime("%I:%M %p") %></p>

        <p> <label> Location: </label> </p>
        <p id= "address"> <%= @event.address %></p>

      
        <p><%= @event.description %></p>
        <p><span>Hosted By:</span> <%=  @event.host_organization.name %> <a class="button" href="#popup1"><%= image_tag("info.png", :class => 'icon pop_i')%> </a></p>
        <p><span>Caterer: </span><%= @event.caterer.name %> <a class="button" href="#popup2"><%= image_tag("info.png", :class => 'icon pop_i')%> </a> </p>


</div>
<% if !current_user.admin %>
<div class="event_buttons">
    <% if current_user.bookmarked_events.include?(@event) %>
        <%= link_to "Remove Bookmark", event_bookmarked_path(@event),  :class=> "bookmark" %> 
    <%else%>
        <%= link_to "Bookmark", event_bookmarked_path(@event), :class=> "bookmark"  %> 
    <%end %>
   
    <% if current_user.attending_events.include?(@event) %> 
        <%= link_to "Not Attending", event_attending_path(@event), :class=> "bookmark" %> 
    <%else%>
        <%= link_to "Attending", event_attending_path(@event), :class=> "bookmark" %> 
    <%end %>
</div> 
<%else %>

    
    <%= form_for @event, url: event_admin_reviews_path(@event), method: :post, :data => {confirm: 'Are you sure that you would like to approve this event?'} do |f| %>
        <%= f.submit "Approve event" %> 
    <% end %> 
    

    <%= form_for @event, url: event_admin_reviews_destroy_path(@event), method: :delete, :data => {confirm: 'Are you sure you would like to delete this event? '} do |f| %>
    <%= f.submit "Delete event" %> 
    <% end %> 


   
    <% if @event.does_require_update  %> 
    <button type="button"  disabled  >Require update</button>
    <% elsif @event.does_require_update == false %> 
        
        <button >Require update</button>
    

        <div class = 'update-form'>
            <%= form_for @event, url: event_admin_reviews_patch_path(@event), method: :put, :data => {confirm: 'Are you sure you would like to require this update?'}, :html => { :class => 'update_form' } do |f| %>
            <h3><%= f.label :update_required_explanation %></h3>
            <br>
            <%= f.text_area :update_required_explanation, size: "35x8" %>
            <%= f.submit "Require event update", :class => 'submit-button' %> 
            <% end %> 
        </div>
    <% end %> 
    

    
        <% if @event.does_require_update %>
            <%= @event.update_required_explanation %> 
        <% end %>


<% end %>
</div>



<div id="map" style="width: 50%; height: 480px;"></div>

</div>
<div id="popup1" class="overlay">
	<div class="popup">
		
		<a class="close" href="#">&times;</a>
		<div class="content">
			<p class="host_name">
            <%= @host_organization.name %>
            </p>
            <p><%= image_tag("home.png", :class => 'icon pop_i')%>
            <%= @host_organization.website %>
            </p>
            <p> <%= image_tag("email.png", :class => 'icon pop_i')%>
            <%= @host_organization.email %>
            </p>
            <p> <%= image_tag("address.png", :class => 'icon pop_i')%>
            <%= @host_organization.mailing_address %>
            </p>
            <p> <%= image_tag("phone.png", :class => 'icon pop_i')%>
            <%= @host_organization.phone_number %>
            </p>
            <p class="desc">
            <%= @host_organization.description%>
            </p>

		</div>
	</div>
</div>

<div id="popup2" class="overlay">
	<div class="popup">
		
		<a class="close" href="#">&times;</a>
		<div class="content">
			<p class="host_name">
            <%= @caterer.name %>
            </p>
            <p> <%= image_tag("home.png", :class => 'icon pop_i')%>
            <%= @caterer.website %>
            </p>
            <p> <%= image_tag("email.png", :class => 'icon pop_i')%>
            <%= @caterer.email %>
            </p>
            <p> <%= image_tag("address.png", :class => 'icon pop_i')%>
            <%= @caterer.mailing_address %>
            </p>
            <p> <%= image_tag("phone.png", :class => 'icon pop_i')%>
            <%= @caterer.phone_number %>
            </p>
            <p class="desc">
            <%= @caterer.description%>
            </p>

		</div>
	</div>
</div>